### PR TITLE
Start using mozci

### PR DESCRIPTION
**Pull request by F3real**

### CODE REVIEW

**Comment by armenzg** [comment]
@chmanchester I will let you know when I believe this PR is ready for you to look at.

Hi @F3real this seems to be going in the right direction, however, GH is making this PR very difficult to review because there are some functions that have been re-sorted and perhaps switching branch for repo_name is making it harder for it to recognize that it is still the same function.

Would you mind putting the functions in the same order and to not rename branch to repo_name?
We can do that on a follow up PR but this one will be easier to review.

You can test how it "compares" by using this before opening a new PR:
https://github.com/chmanchester/trigger-bot/compare/master...F3real:master

**Comment by F3real** [comment]
I don't remember changing order of functions, but maybe fixing style errors caused github to see some functions as changed. I could close this PR and submit adding tox and other style fixes as new PR and when that's reviewed to create new PR with other changes.

**Comment by armenzg** [comment]
Thank you Stefan!

**Comment by armenzg** [comment]
@F3real could we close this PR and open a new one after the other PR gets merged?

**Comment by F3real** [comment]
Sure, I've forgot about it.

**Pull request closed without merging**
