### PR TITLE
Fix call of retrigger functions

### PR DESCRIPTION
**Pull request by F3real**

### CODE REVIEW

**Comment by armenzg** [comment]
I've made a 0.26.0 release of mozci.
This PR's change looks good. @chmanchester feel free to merge once @F3real bumps the release.

@F3real would you mind testing the new version with dry_run now that you have ldap access?

**Comment by F3real** [comment]
@chmanchester  This should be ready for review now :)

**Comment by chmanchester** [comment]
I'm still seeing an issue when I check this locally. The listener runs fine, but when it gets to the triggering step, it logs things like:

```
INFO: Found 0 jobs total for ec33601ba832
WARNING: Up to 51 total triggers have been performed by this service.
INFO: attempt_triggers, attempt 5
WARNING: Could not trigger "Ubuntu VM 12.04 x64 try debug test web-platform-tests-e10s-8" at ec33601ba832 because there were no builds found with that buildername to rebuild.
```

while the current version shows:

```
Mar 07 14:32:29 trigger-bot app/worker.1: INFO: Found 594 jobs total for ec33601ba832 
Mar 07 14:32:29 trigger-bot app/worker.1: WARNING: Up to 541 total triggers have been performed by this service. 
Mar 07 14:32:29 trigger-bot app/worker.1: INFO: attempt_triggers, attempt 0 
Mar 07 14:32:29 trigger-bot app/worker.1: INFO: Triggering url: https://secure.pub.build.mozilla.org/buildapi/self-serve/try/build 
Mar 07 14:32:29 trigger-bot app/worker.1: DEBUG: Triggering payload: 
Mar 07 14:32:29 trigger-bot app/worker.1:   {'count': 1, 'build_id': 101857110} 
Mar 07 14:32:30 trigger-bot app/worker.1: INFO: Requested job, return: 202 
Mar 07 14:32:30 trigger-bot app/worker.1: INFO: Triggered 1 of "Ubuntu VM 12.04 x64 try debug test web-platform-tests-e10s-8" at ec33601ba832 
```

note the message about not finding a job to trigger, there must be a mis-match somewhere. @F3real, can you check on this?

**Comment by F3real** [comment]
Hmm, seems that problem is in **_get_ids_for_rev**. I'll look into it.

**Comment by armenzg** [comment]
What ended up happening here? Did the last code change fix the last issues?

**Comment by F3real** [comment]
It seems that we are getting empty results for some calls of **get_all_jobs**.
In mozci[1]  we are using cache so probably in case of failure of buildapi call, empty results get cached and then returned constantly because there is no cache invalidation/bypass.

[1]https://github.com/mozilla/mozilla_ci_tools/blob/master/mozci/query_jobs.py#L113

**Comment by armenzg** [comment]
That really sucks. Maybe we should remove the caching capability completely until we can invalidate/bypass the cache properly.

**Comment by armenzg** [comment]
I think this looks good.
@chmanchester what are the steps to test this?

**Pull request closed without merging**
